# Generated by Django 4.2.7 on 2026-04-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_work_permit_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='wp_next_number',
            field=models.PositiveIntegerField(default=1, verbose_name='WP Next Number'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='wp_prefix',
            field=models.CharField(default='WP', max_length=10, verbose_name='Work Permit Prefix'),
        ),
    ]
