# Generated by Django 4.2.7 on 2026-04-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_systemsetting_wp_next_number_systemsetting_wp_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermissiontemplate',
            name='perm_wp_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermissiontemplate',
            name='perm_wp_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermissiontemplate',
            name='perm_wp_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermissiontemplate',
            name='perm_wp_view',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rolepermissiontemplate',
            name='perm_wp_write',
            field=models.BooleanField(default=True),
        ),
    ]
